kind: golang.Generate
spec:
  versionPackagePath: internal/version
---
kind: common.SourceAssets
spec:
  images:
    - ref: ghcr.io/siderolabs/ipxe:v1.11.0
      copies:
        - platform: linux/amd64
          source: /usr/libexec/ipxe.efi
          destination: internal/server/ipxe/data/amd64/ipxe.efi
        - platform: linux/amd64
          source: /usr/libexec/snp.efi
          destination: internal/server/ipxe/data/amd64/snp.efi
        - platform: linux/amd64
          source: /usr/libexec/kpxe/undionly.kpxe.bin
          destination: internal/server/ipxe/data/amd64/kpxe/undionly.kpxe.bin
        - platform: linux/amd64
          source: /usr/libexec/kpxe/undionly.kpxe.zinfo
          destination: internal/server/ipxe/data/amd64/kpxe/undionly.kpxe.zinfo
        - platform: linux/arm64
          source: /usr/libexec/ipxe.efi
          destination: internal/server/ipxe/data/arm64/ipxe.efi
        - platform: linux/arm64
          source: /usr/libexec/snp.efi
          destination: internal/server/ipxe/data/arm64/snp.efi
---
kind: common.Image
name: image-booter
spec:
  pushLatest: false
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: service.CodeCov
spec:
  enabled: false
