# commit to be tagged for the new release
commit = "HEAD"

project_name = "booter"
github_repo = "siderolabs/booter"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.3.1"
# pre_release = true

# [notes]
